spring.application.name=EquipmentBookingSystem
server.port=8080

# Khai bao ket noi DB
spring.datasource.url=jdbc:mysql://localhost:3306/cse456_group_project
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Khai bao thong tin jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Thiet lap Thymeleaf
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Session config
server.servlet.session.timeout=30m

# Logging
logging.level.org.springframework.web=INFO
logging.level.eiu.edu.vn=DEBUG