spring.application.name=EquipmentBookingSystem

# Khai bao ket noi DB
spring.datasource.url=jdbc:mysql://localhost:3306/cse456_group_project
spring.datasource.username=root
spring.datasource.password=root

# Khai bao thong tin jpa
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Thiet lap Thymeleaf
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false